### ISSUE TITLE
友链的文字好像有点怪

### ISSUE THREAD

**Issue by inslicc** [ChrAlpha/Friends#4]
今天来访你的博客，顺带看了一下友链部分，发现过长的文字超界了：
![image](https://github.com/ChrAlpha/Friends/assets/148861329/618f8160-8354-4bc1-92c4-309d1bd04943)
![image](https://github.com/ChrAlpha/Friends/assets/148861329/71ad2dfc-8a78-4b20-afa4-5fcc2f7bbb1c)

**Comment by ChrAlpha** [comment]
换行会导致头像显示不正常，取舍过后只好将 Text Overflow 设为 `truncate` 溢出隐藏
